using UnityEngine;

[CreateAssetMenu(fileName = "DataContainer", menuName = "Scriptable Objects/DataContainer")]
public class SerializableProperty : ScriptableObject
{
    [field: Header("Data")] //The field notation for the attribute makes it apply to the backing field generated by the compiler
    [field: SerializeField] public string ObjectName { get; private set; } //This field is read only, you will not be able to modify it without reflection
    [field: SerializeField] public string ObjectDescription { get; private set; }
    [field: SerializeField] public int HP { get; private set; } = 10;
    
    
    [field: SerializeField] public string Variable { get; private set; }
}
